# Change these first
owner: JNA-Dealer-Program # Your GitHub organization or username, where this repository lives
repo: stats # The name of this repository

sites:
  - name: TV Internet Deals
    url: https://www.tvinternetdeals.org
  - name: JNA Dealer
    url: https://www.jnadealerprogram.com
  - name: JNA.Org
    url: https://jna.org
  - name: Wowmover
    url: https://wowmover.com
  - name: Astro Marketing
    url: https://astromarketing.org/
  - name: JNA Retail
    url: https://jnaretail.com/  
  - name: Medicare Service
    url: https://medicareservice.net/
  - name: Home Alarm Security
    url: https://www.homealarmsecurity.org/
  - name: Partnerchannel.org
    url: https://www.Partnerchannel.org/
  - name: Test broken website
    url: https://www.asaasasasasasasasa.orgy/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: jna-dealer-program.github.io
  baseUrl: /stats
  logoUrl: https://www.jnadealerprogram.com/blog/wp-content/uploads/2023/02/jnadplogo.jpg
  name: Monitoring
  introTitle: "Monitor and Status page"
  introMessage: This is a status page which uses **real-time** data from JNA Dealer Websites
  links:
    - rel: stylesheet
      href: https://jna-dealer-program.github.io/global.css


i18n:
  footer: ©️ Jeff Gaboni 2022, Powered by [Upptime](https://upptime.js.org/).
  liveStatus: Service Status
  allSystemsOperational: All services are operational! 
  
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
